// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export function AddDownload(input: contracts$0.AddDownloadRequest): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(1885975102, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AttachApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3299756405, app);
}

export function Bootstrap(): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(3925993807).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenDownloadDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3495293194);
}

export function OpenDownloadFolder(gid: string): $CancellablePromise<void> {
    return $Call.ByID(1267030031, gid);
}

export function OpenDownloadedFile(gid: string): $CancellablePromise<void> {
    return $Call.ByID(3432732940, gid);
}

export function OpenWebsite(url: string): $CancellablePromise<void> {
    return $Call.ByID(432486228, url);
}

export function PauseAll(): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(2306838046).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PauseDownload(gid: string): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(4093712591, gid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PickAria2Binary(): $CancellablePromise<string> {
    return $Call.ByID(3994132650);
}

export function PickDownloadDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1561511285);
}

export function Refresh(): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(1192522998).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveDownload(input: contracts$0.RemoveDownloadRequest): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(964124715, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ResumeAll(): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(336967147).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ResumeDownload(gid: string): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(1251659992, gid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RetryDownload(gid: string): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(2474168767, gid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RevealPreferencesFile(): $CancellablePromise<void> {
    return $Call.ByID(2366123290);
}

export function SavePreferences(prefs: contracts$0.Preferences): $CancellablePromise<contracts$0.AppSnapshot> {
    return $Call.ByID(3178187444, prefs).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = contracts$0.AppSnapshot.createFrom;
