//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../../../../shreyam1008/gobarrygo/internal/contracts/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "app:notification": $$createType0,
        "app:snapshot": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.Notification.createFrom;
const $$createType1 = contracts$0.AppSnapshot.createFrom;

configure();
