// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddDownloadRequest {
    "urls": string[];
    "directory": string;
    "outputName": string;
    "headers": string[];
    "userAgent": string;

    /** Creates a new AddDownloadRequest instance. */
    constructor($$source: Partial<AddDownloadRequest> = {}) {
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("outputName" in $$source)) {
            this["outputName"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddDownloadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddDownloadRequest {
        const $$createField0_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField0_0($$parsedSource["urls"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new AddDownloadRequest($$parsedSource as Partial<AddDownloadRequest>);
    }
}

export class AppSnapshot {
    "version": VersionInfo;
    "health": Health;
    "metrics": Metrics;
    "preferences": Preferences;
    "downloads": DownloadItem[];

    /** Creates a new AppSnapshot instance. */
    constructor($$source: Partial<AppSnapshot> = {}) {
        if (!("version" in $$source)) {
            this["version"] = (new VersionInfo());
        }
        if (!("health" in $$source)) {
            this["health"] = (new Health());
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = (new Metrics());
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = (new Preferences());
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSnapshot {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField0_0($$parsedSource["version"]);
        }
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField1_0($$parsedSource["health"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField2_0($$parsedSource["metrics"]);
        }
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField3_0($$parsedSource["preferences"]);
        }
        if ("downloads" in $$parsedSource) {
            $$parsedSource["downloads"] = $$createField4_0($$parsedSource["downloads"]);
        }
        return new AppSnapshot($$parsedSource as Partial<AppSnapshot>);
    }
}

export class DownloadFile {
    "index": number;
    "path": string;
    "length": number;
    "completedLength": number;
    "selected": boolean;
    "uris": string[];

    /** Creates a new DownloadFile instance. */
    constructor($$source: Partial<DownloadFile> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("completedLength" in $$source)) {
            this["completedLength"] = 0;
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }
        if (!("uris" in $$source)) {
            this["uris"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadFile {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uris" in $$parsedSource) {
            $$parsedSource["uris"] = $$createField5_0($$parsedSource["uris"]);
        }
        return new DownloadFile($$parsedSource as Partial<DownloadFile>);
    }
}

export class DownloadItem {
    "gid": string;
    "name": string;
    "status": string;
    "directory": string;
    "totalLength": number;
    "completedLength": number;
    "progress": number;
    "downloadSpeed": number;
    "uploadSpeed": number;
    "connections": number;
    "etaSeconds": number;
    "errorCode": string;
    "errorMessage": string;
    "files": DownloadFile[];

    /** Creates a new DownloadItem instance. */
    constructor($$source: Partial<DownloadItem> = {}) {
        if (!("gid" in $$source)) {
            this["gid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("totalLength" in $$source)) {
            this["totalLength"] = 0;
        }
        if (!("completedLength" in $$source)) {
            this["completedLength"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            this["downloadSpeed"] = 0;
        }
        if (!("uploadSpeed" in $$source)) {
            this["uploadSpeed"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("etaSeconds" in $$source)) {
            this["etaSeconds"] = 0;
        }
        if (!("errorCode" in $$source)) {
            this["errorCode"] = "";
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadItem {
        const $$createField13_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField13_0($$parsedSource["files"]);
        }
        return new DownloadItem($$parsedSource as Partial<DownloadItem>);
    }
}

export class Health {
    "ready": boolean;
    "status": string;
    "message": string;
    "binaryPath": string;
    "rpcPort": number;

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("binaryPath" in $$source)) {
            this["binaryPath"] = "";
        }
        if (!("rpcPort" in $$source)) {
            this["rpcPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Health($$parsedSource as Partial<Health>);
    }
}

export class Metrics {
    "activeCount": number;
    "waitingCount": number;
    "stoppedCount": number;
    "totalCount": number;
    "downloadSpeed": number;
    "uploadSpeed": number;

    /** Creates a new Metrics instance. */
    constructor($$source: Partial<Metrics> = {}) {
        if (!("activeCount" in $$source)) {
            this["activeCount"] = 0;
        }
        if (!("waitingCount" in $$source)) {
            this["waitingCount"] = 0;
        }
        if (!("stoppedCount" in $$source)) {
            this["stoppedCount"] = 0;
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            this["downloadSpeed"] = 0;
        }
        if (!("uploadSpeed" in $$source)) {
            this["uploadSpeed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metrics instance from a string or object.
     */
    static createFrom($$source: any = {}): Metrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metrics($$parsedSource as Partial<Metrics>);
    }
}

export class Notification {
    "kind": string;
    "title": string;
    "message": string;

    /** Creates a new Notification instance. */
    constructor($$source: Partial<Notification> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     */
    static createFrom($$source: any = {}): Notification {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notification($$parsedSource as Partial<Notification>);
    }
}

export class Preferences {
    "aria2Binary": string;
    "downloadDirectory": string;
    "maxConcurrentDownloads": number;
    "split": number;
    "maxConnectionsPerServer": number;
    "minSplitSize": string;
    "fileAllocation": string;
    "continueDownloads": boolean;
    "alwaysResume": boolean;
    "autoRename": boolean;
    "userAgent": string;
    "notifyOnCompletion": boolean;
    "notifyOnError": boolean;

    /** Creates a new Preferences instance. */
    constructor($$source: Partial<Preferences> = {}) {
        if (!("aria2Binary" in $$source)) {
            this["aria2Binary"] = "";
        }
        if (!("downloadDirectory" in $$source)) {
            this["downloadDirectory"] = "";
        }
        if (!("maxConcurrentDownloads" in $$source)) {
            this["maxConcurrentDownloads"] = 0;
        }
        if (!("split" in $$source)) {
            this["split"] = 0;
        }
        if (!("maxConnectionsPerServer" in $$source)) {
            this["maxConnectionsPerServer"] = 0;
        }
        if (!("minSplitSize" in $$source)) {
            this["minSplitSize"] = "";
        }
        if (!("fileAllocation" in $$source)) {
            this["fileAllocation"] = "";
        }
        if (!("continueDownloads" in $$source)) {
            this["continueDownloads"] = false;
        }
        if (!("alwaysResume" in $$source)) {
            this["alwaysResume"] = false;
        }
        if (!("autoRename" in $$source)) {
            this["autoRename"] = false;
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("notifyOnCompletion" in $$source)) {
            this["notifyOnCompletion"] = false;
        }
        if (!("notifyOnError" in $$source)) {
            this["notifyOnError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     */
    static createFrom($$source: any = {}): Preferences {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences($$parsedSource as Partial<Preferences>);
    }
}

export class RemoveDownloadRequest {
    "gid": string;
    "deleteFiles": boolean;

    /** Creates a new RemoveDownloadRequest instance. */
    constructor($$source: Partial<RemoveDownloadRequest> = {}) {
        if (!("gid" in $$source)) {
            this["gid"] = "";
        }
        if (!("deleteFiles" in $$source)) {
            this["deleteFiles"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoveDownloadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoveDownloadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoveDownloadRequest($$parsedSource as Partial<RemoveDownloadRequest>);
    }
}

export class VersionInfo {
    "number": string;
    "codename": string;

    /** Creates a new VersionInfo instance. */
    constructor($$source: Partial<VersionInfo> = {}) {
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("codename" in $$source)) {
            this["codename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo($$parsedSource as Partial<VersionInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = VersionInfo.createFrom;
const $$createType2 = Health.createFrom;
const $$createType3 = Metrics.createFrom;
const $$createType4 = Preferences.createFrom;
const $$createType5 = DownloadItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = DownloadFile.createFrom;
const $$createType8 = $Create.Array($$createType7);
