# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: ShreyamAdhikari.GoBarryGo
PackageVersion: 0.0.8
ManifestType: installer
ManifestVersion: 1.6.0

InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install

Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/shreyam1008/gobarrygo/releases/download/v0.0.8/gobarrygo-amd64-installer.exe
    InstallerSha256: 532a1f33c93a044bfe87255a77f21746cc333bb6ce34f821605389403f1a3b5b
